language: go

go:
  - 1.5.3

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gradle
  - cd $GOPATH/src/github.com/thatguystone/cog/internal/testing && ./run.sh travis

script:
  - go generate ./...
  - go test ./...
