language: go

go:
  - 1.5.3

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gradle
  - cd $GOPATH/github.com/thatguystone/cog/cio/eio/kafka/local && ./run.sh travis

script:
  - go generate ./...
  - go test ./...
